const boardEl = document.querySelector('#board');
const moveList = document.querySelector('#moveList');
const statusTitle = document.querySelector('#statusTitle');
const statusDetail = document.querySelector('#statusDetail');
const modal = document.querySelector('#modal');
const pieceChars={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
const initial=()=>['br','bn','bb','bq','bk','bb','bn','br','bp','bp','bp','bp','bp','bp','bp','bp',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'wp','wp','wp','wp','wp','wp','wp','wp','wr','wn','wb','wq','wk','wb','wn','wr'];
let state, mode='ai', aiTimer, clockTimer;
function reset(){clearTimeout(aiTimer);clearInterval(clockTimer);state={board:initial(),turn:'w',selected:null,legal:[],moves:[],last:null,castling:{w:{k:true,q:true},b:{k:true,q:true}},enPassant:null,gameOver:false,clocks:{w:600,b:600},thinking:false};modal.classList.add('hidden');render();clockTimer=setInterval(tickClock,1000);}
function tickClock(){if(!state||state.gameOver)return;state.clocks[state.turn]=Math.max(0,state.clocks[state.turn]-1);const format=seconds=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;document.querySelector('#whiteClock').textContent=format(state.clocks.w);document.querySelector('#blackClock').textContent=format(state.clocks.b);if(state.clocks[state.turn]===0){const winner=state.turn==='w'?'Black':'White';state.gameOver=true;clearInterval(clockTimer);showGameOver('Time out',`${winner} wins on time.`);render();}}
const rc=i=>[Math.floor(i/8),i%8], idx=(r,c)=>r*8+c, inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
function pseudoMoves(from, attack=false){const p=state.board[from];if(!p)return[];const color=p[0],type=p[1],[r,c]=rc(from),out=[];const add=(rr,cc,extra={})=>{if(inside(rr,cc)){let target=state.board[idx(rr,cc)];if(!target||target[0]!==color)out.push({to:idx(rr,cc),...extra});}};const rays=(dirs)=>dirs.forEach(([dr,dc])=>{for(let rr=r+dr,cc=c+dc;inside(rr,cc);rr+=dr,cc+=dc){let t=state.board[idx(rr,cc)];if(!t||t[0]!==color)out.push({to:idx(rr,cc)});if(t)break;}});
 if(type==='p'){let d=color==='w'?-1:1,start=color==='w'?6:1;for(const dc of[-1,1]){let rr=r+d,cc=c+dc;if(!inside(rr,cc))continue;let target=state.board[idx(rr,cc)];if(attack||target&&target[0]!==color||state.enPassant===idx(rr,cc))out.push({to:idx(rr,cc),enPassant:!attack&&state.enPassant===idx(rr,cc)});}if(!attack&&!state.board[idx(r+d,c)]){out.push({to:idx(r+d,c)});if(r===start&&!state.board[idx(r+2*d,c)])out.push({to:idx(r+2*d,c),double:true});}}
 else if(type==='n')[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(x=>add(r+x[0],c+x[1]));else if(type==='b')rays([[1,1],[1,-1],[-1,1],[-1,-1]]);else if(type==='r')rays([[1,0],[-1,0],[0,1],[0,-1]]);else if(type==='q')rays([[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]]);else{for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attack&&state.castling[color].k&&!state.board[idx(r,c+1)]&&!state.board[idx(r,c+2)]&&!inCheck(color)&&!squareAttacked(idx(r,c+1),color)&&!squareAttacked(idx(r,c+2),color))out.push({to:idx(r,c+2),castle:'k'});if(!attack&&state.castling[color].q&&!state.board[idx(r,c-1)]&&!state.board[idx(r,c-2)]&&!state.board[idx(r,c-3)]&&!inCheck(color)&&!squareAttacked(idx(r,c-1),color)&&!squareAttacked(idx(r,c-2),color))out.push({to:idx(r,c-2),castle:'q'});}return out;}
function squareAttacked(square, byColor){return state.board.some((p,i)=>p&&p[0]!==byColor&&pseudoMoves(i,true).some(m=>m.to===square));}
function inCheck(color){const king=state.board.findIndex(p=>p===color+'k');return squareAttacked(king,color);}
function validMoves(from){return pseudoMoves(from).filter(m=>{const snapshot=state.board.slice(), ep=state.enPassant;applyMove(from,m,true);let bad=inCheck(state.turn);state.board=snapshot;state.enPassant=ep;return !bad;});}
function applyMove(from,m,simulation=false){const p=state.board[from], [r,c]=rc(from),[tr,tc]=rc(m.to);state.board[m.to]=p;state.board[from]=null;if(m.enPassant)state.board[idx(r,tc)]=null;if(m.castle){const rookFrom=idx(r,m.castle==='k'?7:0),rookTo=idx(r,m.castle==='k'?5:3);state.board[rookTo]=state.board[rookFrom];state.board[rookFrom]=null;}if(p[1]==='p'&&(tr===0||tr===7))state.board[m.to]=p[0]+'q';if(!simulation){state.enPassant=m.double?idx((r+tr)/2,c):null;if(p[1]==='k')state.castling[p[0]]={k:false,q:false};if(p[1]==='r'){if(from===56)state.castling.w.q=false;if(from===63)state.castling.w.k=false;if(from===0)state.castling.b.q=false;if(from===7)state.castling.b.k=false;}}}
function notation(p,from,m,captured){let name=p[1]==='p'?'':p[1].toUpperCase();let cap=captured||m.enPassant?'x':'';let file='abcdefgh'[rc(from)[1]];if(p[1]==='p'&&cap)name=file;let promotion=p[1]==='p'&&(rc(m.to)[0]===0||rc(m.to)[0]===7)?'=Q':'';return m.castle?(m.castle==='k'?'O-O':'O-O-O'):name+cap+'abcdefgh'[rc(m.to)[1]]+promotion;}
function finishTurn(){state.turn=state.turn==='w'?'b':'w';state.selected=null;state.legal=[];const movesAvailable=state.board.some((x,j)=>x&&x[0]===state.turn&&validMoves(j).length);if(!movesAvailable){state.gameOver=true;showGameOver(inCheck(state.turn)?'Checkmate':'Stalemate',inCheck(state.turn)?`${state.turn==='w'?'Black':'White'} wins the match.`:'The game is drawn.');}render();if(mode==='ai'&&state.turn==='b'&&!state.gameOver){state.thinking=true;render();aiTimer=setTimeout(aiMove,450);}}
function commitMove(from,move){const moving=state.board[from],captured=state.board[move.to],text=notation(moving,from,move,captured);applyMove(from,move);state.last=[from,move.to];state.moves.push(text);finishTurn();}
function handleClick(i){if(state.gameOver||state.thinking||(mode==='ai'&&state.turn==='b'))return;let p=state.board[i];if(state.selected===null){if(p&&p[0]===state.turn){state.selected=i;state.legal=validMoves(i);render();}return;}let move=state.legal.find(m=>m.to===i);if(!move){state.selected=p&&p[0]===state.turn?i:null;state.legal=state.selected!==null?validMoves(i):[];render();return;}commitMove(state.selected,move);}
function aiMove(){if(state.gameOver||mode!=='ai'||state.turn!=='b')return;state.thinking=false;let options=[];state.board.forEach((p,from)=>{if(p&&p[0]==='b')validMoves(from).forEach(move=>{let captured=state.board[move.to];let value={p:10,n:30,b:31,r:50,q:90,k:0}[captured?.[1]]||0;let[,col]=rc(move.to);options.push({from,move,score:value+(col>=2&&col<=5?2:0)+Math.random()*6});});});options.sort((a,b)=>b.score-a.score);if(options[0])commitMove(options[0].from,options[0].move);}
function render(){boardEl.innerHTML='';state.board.forEach((p,i)=>{let[r,c]=rc(i),btn=document.createElement('button');btn.className=`square ${(r+c)%2?'dark':'light'} ${state.selected===i?'selected':''} ${state.last?.includes(i)?'last':''}`;let m=state.legal.find(x=>x.to===i);if(m)btn.classList.add(state.board[i]||m.enPassant?'capture':'legal');btn.setAttribute('aria-label',p?`${p[0]==='w'?'White':'Black'} ${p[1]}`:`${'abcdefgh'[c]}${8-r}`);let labels=`${c===0?`<span class="rank-label">${8-r}</span>`:''}${r===7?`<span class="file-label">${'ABCDEFGH'[c]}</span>`:''}`;btn.innerHTML=labels+(p?`<span class="piece ${p[0]==='w'?'white':'black'}">${pieceChars[p[0]][p[1]]}</span>`:'');btn.onclick=()=>handleClick(i);boardEl.append(btn);});moveList.innerHTML='';for(let i=0;i<state.moves.length;i+=2){let li=document.createElement('li');li.innerHTML=`<span class="turn">${i/2+1}.</span>${state.moves[i]||''} ${state.moves[i+1]||''}`;moveList.append(li);}let local=mode==='local',who=local?(state.turn==='w'?'White’s':'Black’s'):(state.turn==='w'?'Your':'AI’s');statusTitle.textContent=state.gameOver?'Game over':state.thinking?'AI is thinking…':`${who} move`;statusDetail.textContent=state.gameOver?'Start a new game to play again.':local?`${state.turn==='w'?'White':'Black'} to play`:(state.turn==='w'?'You play White':'Chess AI plays Black');document.querySelector('#whiteClock').classList.toggle('active-clock',state.turn==='w');document.querySelector('#blackClock').classList.toggle('active-clock',state.turn==='b');document.querySelector('#opponentName').textContent=local?'Black player':'Chess AI';document.querySelector('#opponentMeta').textContent=local?'Pass-and-play':'Adaptive opponent';document.querySelector('#opponentAvatar').textContent=local?'P2':'AI';document.querySelector('#gameType').textContent=local?'LOCAL 2 PLAYER • 10 MIN':'VS AI • 10 MIN';document.querySelector('#gameTitle').textContent=local?'Two-player chess':'1v1 Chess';document.querySelector('#hint').textContent=local?'Pass the device after each move.':'You are White. The AI plays Black.';}
function showGameOver(title,text){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalText').textContent=text;modal.classList.remove('hidden');}
document.querySelector('#newGameButton').onclick=reset;document.querySelector('#playAgain').onclick=reset;document.querySelector('#resignButton').onclick=()=>{if(!state.gameOver){clearTimeout(aiTimer);state.gameOver=true;showGameOver('Resignation',`${state.turn==='w'?'Black':'White'} wins the match.`);render();}};document.querySelector('#undoButton').onclick=()=>reset();document.querySelectorAll('.mode').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===button));reset();});
reset();
